### ISSUE TITLE
Support depresolve on raw NPMjs

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib-javascript#10]
Most packages on NPM won't have a github repo attached to them.

Currently it seems like srclib just fails to resolve dependencies when they don't have a github url attached to it.

In reality all of these dependencies can be resolved to `https://www.npmjs.org/package/[PACKAGE NAME]`.  In fact github is less ideal than npmjs because head on a git repository is not necessarily version as represented by npmjs releases.  This will lead to inaccurate builds.

Related: https://github.com/sourcegraph/srclib/issues/105

**Comment by xizhao** [comment]
note: does it support peerdeps? I'll look into this later.

**Comment by beyang** [comment]
Currently, srclib assumes all dependencies are resolvable to a git repository, but this assumption breaks for a lot of package management systems, including the case mentioned above. FYI, in the near future, we want to move to a model that doesn't make this assumption, so we can have source units that are found at arbitrary URLs (not just ones that resolve to git repositories).

**Comment by xizhao** [comment]
We already have an "archive" VCS type that we define in pydep.  "NPM" can be considered a VCS and will be used as the method to checkout code from the registry anyways.

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
