### ISSUE TITLE
Depresolve doesn't resolve to correct revspec

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib-javascript#15]
Depresolve doesn't resolve to the correct version -- but instead picks a version returned by npm listings.  There reverse also happens, where it also tries to resolve npm packages `package@version` into `giturl@head`, ignoring the corresponding rev.

There's not really a way to correspond an npm release version with a git rev id without parsing previous commits and diffs of the package.json, and even then you won't get a real answer without comparing files from the published release to the rev.

I think this encompasses a greater problem that srclib tries to resolve everything to a git url, which is inconsistent in at least 10% of cases.

Instead i think the model should be:

- srcunit
- fetcher (i.e. git, npm)
- fetcher spec (i.e. revspec, semver)

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
