### ISSUE TITLE
Get rid of node manual dep

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib-javascript#16]
We don't know if it's node, iojs, etc...

NPM can be used as a dep manager for frontend code as well, or anything else.

**Comment by xizhao** [comment]
Node on npm also doesn't install node: 
https://www.npmjs.com/package/node

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
