### ISSUE TITLE
Format JavaScript display names nicely

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-javascript#23]
JavaScript definition names are not pretty (see below). Displayed names should be human readable.

![image](https://cloud.githubusercontent.com/assets/1646931/15101199/82fd1c6e-153e-11e6-929e-023ed395ec2e.png)

**Comment by antonina-cherednichenko** [comment]
After investigation of the issue, I am a bit confused:

1. Symbol _fn(values: [[?, [?]]])_ corresponds to definition _dist/async.js/fn/1/fn/MapCache_ which originally has type - _fn(values: [[**string,** ?]])_

2. Symbol   [[?, [?]] corresponds to definition _dist/async.js/fn/1/fn/MapCache/param/values_ which originally has type _[[string, ?]]_

3. Symbol  var [?, [?]] corresponds to definition _dist/async.js/fn/1/fn/MapCache/var/entry_ which originally has type _[string, ?]_

So it's looks like some info is missing in symbol representation, string type at least somehow disappeared.
Needs some clarification from UI team here. Thanks!

**Comment by alexsaveliev** [comment]
I'll try to adjust Go code that formats the data

**Comment by alexsaveliev** [comment]
claimed fixed by #54, requires update of `sourcegraph`
