### ISSUE TITLE
Async library issues

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-javascript#25]
https://sourcegraph.com/github.com/caolan/async

None of the top-level files in the `lib` directory seem to work.
For example, https://sourcegraph.com/github.com/caolan/async@master/-/blob/lib/apply.js -- definitions highlight on hover, but you can't click on them (404)

**Comment by alexsaveliev** [comment]
Path generation is fixed in [issue-25](/alexsaveliev/srclib-javascript/tree/issue-25)

@antonina-cherednichenko, could you please investigate why there are the following refs:

```
{
 +      "DefPath": "issue-25-import/index.js/import/rest",
 +      "File": "issue-25-import/index.js",
 +      "Start": 100,
 +      "End": 104
 +    },
 +    {
 +      "DefPath": "issue-25-import/index.js/import/rest",
 +      "File": "issue-25-import/index.js",
 +      "Start": 63,
 +      "End": 67
 +    }
```
which have no matching defs?
