### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/srclib-javascript#26]
_From @alexsaveliev on May 6, 2016 9:58_

I see no reason of not having Windows support for srclib-javascript. 

- Please make sure that everywhere where file path are emitted, Unix-style separators (slash) are used to produce test results consistent with the expected data
- Please add `srclib-javascript.bat` file to run nodejs with the proper arguments 

_Copied from original issue: alexsaveliev/srclib-javascript#3_

**Comment by alexsaveliev** [comment]
@antonina-cherednichenko , could you please review my changes?

**Comment by antonina-cherednichenko** [comment]
LGTM
