### ISSUE TITLE
srclib-javascript `index.js` hangs indefinitely

### ISSUE THREAD

**Issue by beyang** [sourcegraph/srclib-javascript#36]
This page hangs indefinitely for some reason: https://sourcegraph.com/github.com/sourcegraph/srclib-javascript@master/-/blob/index.js

**Comment by antonina-cherednichenko** [comment]
This file is an empty file, so this is the reason of such strange behaviour. I was originally empty, so I've deleted it in the last commit. 

Probably UI should be checked, why behaviour is so unusual for empty files.

**Comment by beyang** [comment]
great, thanks for looking into this, Antonina
