### ISSUE TITLE
Linked value exported by node stdlib has incorrect URL hash

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-javascript#38]
Here: https://sourcegraph.com/github.com/expressjs/express@master/-/blob/lib/express.js

Token: http://cl.ly/2a1i2G2Y113r
Expected URL: https://nodejs.org/api/events.html#events_class_eventemitter
Actual URL: https://nodejs.org/api/events.html#events_class_events_eventemitter

**Comment by alexsaveliev** [comment]
It seems that `node` `tern`'s plugin contains outdated information, related to #40

**Comment by antonina-cherednichenko** [comment]
Outdated def https://github.com/ternjs/tern/blob/master/plugin/node.js#L69

Will be fix in https://github.com/sourcegraph/srclib-javascript/issues/44

**Comment by alexsaveliev** [comment]
closed by #51
