### ISSUE TITLE
404 External link to console.log 

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-javascript#40]
Click on `log` here: https://sourcegraph.com/github.com/sgtest/js-misc@master/-/blob/dir-not-file/lib/index.js

Expected: https://nodejs.org/api/console.html#console_console_log_data
Actual: https://nodejs.org/api/stdio.html#stdio_console_log_data

**Comment by alexsaveliev** [comment]
It seems that `node` `tern`'s plugin contains outdated information

**Comment by antonina-cherednichenko** [comment]
Yes, unfortunately node plugin for tern contains outdated def https://github.com/ternjs/tern/blob/master/plugin/node.js#L2663

I've created new issue for general task of update and review https://github.com/sourcegraph/srclib-javascript/issues/44
