### ISSUE TITLE
Incorrect coverage report stats of JS repos

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-javascript#41]
E.g. http://cl.ly/1d3q2a1y3W2R

^^ generated via `src --endpoint=https://sourcegraph.com coverage --lang="JavaScript"`

We shouldn't be seeing any file scores > 1; many rows are empty (I assume this is because the build fails / there is no build data at all; verified with only a couple repos), and the "Covered files" # for many rows is suspiciously low...e.g. for https://sourcegraph.com/github.com/nodejs/node it says there's only 1 uncovered file (`deps/npm/test/fixtures/onload.js`) but just clicking around that repo you will see most files are unlinked (and, also, the builds page shows no builds have happened: https://sourcegraph.com/github.com/nodejs/node@master/-/builds/?filter=all).

@antonina-cherednichenko since we're going to be measuring srclib-javascript progress by the coverage stats, can you look into what's causing the issues above and get them resolved?

**Comment by rothfels** [comment]
@antonina-cherednichenko -- I think you've been using a different script to report coverage stats than the one referenced above. Am I correct? If so, can you link me to the coverage script you've been running?

**Comment by antonina-cherednichenko** [comment]
Yes, you are right, I am using a bit different approach, not coverage command. I don't have separate script, some statistics data is calculated during 'graph' analysis process. At the end I see result in the form (example): 
_debug: All ids =  615  Undefined ids =  67
debug: percentage of undefined ids =  10.894308943089431 %_

**Comment by alexsaveliev** [comment]
Taking ownership because the results of `src coverage` coming from `srclib`and javascript toolchain is not responsible for them.

**Comment by alexsaveliev** [comment]
Closing this one as obsolete because we are about to change coverage calculation method
