### ISSUE TITLE
Client-sided javascript

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib-javascript#5]
I know this is already a todo, but I thought I'd throw in some suggestions for low-hanging fruit for the ledger.

1. Scan `bower.json` files and `component.json` files for packages.
2. Hard-code in some commonly known js, maybe in a `COMMON_PKG.json` with a schema like: 
```
[{
   "dep_name": function(path, file_contents) { ... } //return dep version signature or repo URL if it's a match
}]
```
`path` being either the filepath or in the dir tree or the contents of `src` in a script tag.  In the README then advocate for people to fork to add other common sources.  By default we can even just try to grep and match with a popular frontend package repository.  `jquery`, `underscore`, and etc. could be a few.  We can leave the rest unresolved, but at least they're there and tracked (I am sure this is very useful for many PMs who want to track 3rd party code).

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
