### ISSUE TITLE
Handle alternative NPM install signatures

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib-javascript#7]
NPM also supports repo URLs and archives, but `npm view` doesn't work on those.  They are fairly important to resolve, as they are also proper npm packages and there are many reasons why would you would put `npm install https://github.com/user/repo` as a dependency.

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
