### ISSUE TITLE
bower_components, node_modules, etc., dirs aren't ignored if not at root

### ISSUE THREAD

**Issue by sqs** [sourcegraph/srclib-javascript#9]
A top-level `bower_components` dir will be ignored, but a `foo/bar/bower_components/baz` dir isn't.

**Comment by xizhao** [comment]
We can be smarter about comparing node modules to package.json.

If the package.json lists no deps, we can assume that deps are vendorized.  We can still skip all files, but pull just the package.json details from each folder in node_modules for dep information.

**Comment by beyang** [comment]
We're restarting development on this, so closing outstanding issues for now since they are likely out of date. Please re-open if still relevant.
